; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define Arch "x86_64"

[Setup]
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64

#include "common.iss"