; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define Arch "x86"

[Setup]
ArchitecturesAllowed=x86

#include "common.iss"